.PHONY: run-task-1 run-task-2 run-task-3 run-task-4

run-task-1:
	@gcc task1.c -o task1 -Wextra -Wall -Wpedantic && ./task1 > valid.txt && cat valid.txt

run-task-2:
	@gcc task2.c -o task2 -Wextra -Wall -Wpedantic && ./task2 > greenvalues.txt && cat greenvalues.txt


run-task-3:

